### ISSUE TITLE
[vue-router] "path" is required in a route configuration

### ISSUE THREAD

**Issue by ijijni** [deatil/larke-admin-frontend#1]
按照你的方法操作后，在登录界面点登陆后，跳转到dashboard的时候老提示[vue-router] "path" is required in a route configuration，你有出现过这个问题吗，排查发现是路由加载报错。[Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode function，解决了很久也没搞定
![image](https://user-images.githubusercontent.com/16640527/104084976-f685ef00-5286-11eb-8db9-914c4a1f98d9.png)

**Comment by ijijni** [comment]
要是你也能用的话，我怀疑是环境造成的。能说说你的运行环境吗，node使用的哪个版本，npm使用的哪个版本

**Comment by deatil** [comment]
> 编译环境

 - node v9.9.0
 
 - npm 6.14.8

**Comment by deatil** [comment]
你这个报错好像是版本跟vue-element-admin需要的版本有出入

**Comment by deatil** [comment]
看他们的说法是你编译用了严格模式，这个版本有些没有用严格模式，需要编译取消严格模式
