### ISSUE TITLE
[Bug]: 登陆成功前端不跳转。node报错，请问怎么处理？

### ISSUE THREAD

**Issue by JokerFy** [deatil/larke-admin-frontend#5]
### larke-admin-frontend 版本

1.0

### Golang 版本

laravel

### 是否依旧存在

可以

### bug描述

1.按照你的文档操作
2.点击登陆，显示登录，但是未跳转
[Vue warn]: data functions should return an object:
https://vuejs.org/v2/guide/components.html#data-Must-Be-a-Function

(found in <Root>)
warn @ vue.runtime.esm.js:619
initData @ vue.runtime.esm.js:4703
initState @ vue.runtime.esm.js:4636
Vue._init @ vue.runtime.esm.js:5000
VueComponent @ vue.runtime.esm.js:5148
Message @ element-ui.common.js:30540
main_Message.<computed> @ element-ui.common.js:30569
_callee$ @ permission.js:51
tryCatch @ regeneratorRuntime.js:44
eval @ regeneratorRuntime.js:125
eval @ regeneratorRuntime.js:69
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
eval @ asyncToGenerator.js:27
eval @ asyncToGenerator.js:19
eval @ permission.js:69
iterator @ vue-router.esm.js:1935
step @ vue-router.esm.js:1709
step @ vue-router.esm.js:1713
runQueue @ vue-router.esm.js:1717
confirmTransition @ vue-router.esm.js:1964
transitionTo @ vue-router.esm.js:1866
replace @ vue-router.esm.js:2279
eval @ vue-router.esm.js:1950
_callee$ @ permission.js:47
tryCatch @ regeneratorRuntime.js:44
eval @ regeneratorRuntime.js:125
eval @ regeneratorRuntime.js:69
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
eval @ asyncToGenerator.js:27
eval @ asyncToGenerator.js:19
eval @ permission.js:69
iterator @ vue-router.esm.js:1935
step @ vue-router.esm.js:1709
step @ vue-router.esm.js:1713
runQueue @ vue-router.esm.js:1717
confirmTransition @ vue-router.esm.js:1964
transitionTo @ vue-router.esm.js:1866
replace @ vue-router.esm.js:2279
eval @ vue-router.esm.js:1950
_callee$ @ permission.js:47
tryCatch @ regeneratorRuntime.js:44
eval @ regeneratorRuntime.js:125
eval @ regeneratorRuntime.js:69
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
eval @ asyncToGenerator.js:27
eval @ asyncToGenerator.js:19
eval @ permission.js:69
iterator @ vue-router.esm.js:1935
step @ vue-router.esm.js:1709
step @ vue-router.esm.js:1713
runQueue @ vue-router.esm.js:1717
confirmTransition @ vue-router.esm.js:1964
transitionTo @ vue-router.esm.js:1866
replace @ vue-router.esm.js:2279
eval @ vue-router.esm.js:1950
_callee$ @ permission.js:47
tryCatch @ regeneratorRuntime.js:44
eval @ regeneratorRuntime.js:125
eval @ regeneratorRuntime.js:69
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
eval @ asyncToGenerator.js:27
eval @ asyncToGenerator.js:19
eval @ permission.js:69
iterator @ vue-router.esm.js:1935
step @ vue-router.esm.js:1709
step @ vue-router.esm.js:1713
runQueue @ vue-router.esm.js:1717
confirmTransition @ vue-router.esm.js:1964
transitionTo @ vue-router.esm.js:1866
replace @ vue-router.esm.js:2279
eval @ vue-router.esm.js:1950
_callee$ @ permission.js:47
tryCatch @ regeneratorRuntime.js:44
eval @ regeneratorRuntime.js:125
eval @ regeneratorRuntime.js:69
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
eval @ asyncToGenerator.js:27
eval @ asyncToGenerator.js:19
eval @ permission.js:69
iterator @ vue-router.esm.js:1935
step @ vue-router.esm.js:1709
step @ vue-router.esm.js:1713
runQueue @ vue-router.esm.js:1717
confirmTransition @ vue-router.esm.js:1964
transitionTo @ vue-router.esm.js:1866
push @ vue-router.esm.js:2267
push @ vue-router.esm.js:2529
eval @ index.vue:221
Promise.then (async)
eval @ index.vue:219
eval @ element-ui.common.js:22992
eval @ element-ui.common.js:23510
complete @ index.js:89
eval @ index.js:225
next @ util.js:148
next @ util.js:116
cb @ index.js:173
validateCaptcha @ index.vue:112
eval @ index.js:216
next @ util.js:114
asyncSerialArray @ util.js:120
eval @ util.js:154
asyncMap @ util.js:151
validate @ index.js:141
validate @ element-ui.common.js:23506
eval @ element-ui.common.js:22986
validate @ element-ui.common.js:22985
handleLogin @ index.vue:216
click @ index.vue:219
invokeWithErrorHandling @ vue.runtime.esm.js:1854
invoker @ vue.runtime.esm.js:2179
original._wrapper @ vue.runtime.esm.js:6911
vue.runtime.esm.js:619 [Vue warn]: Property "visible" must be accessed with "$data.visible" because properties starting with "$" or "_" are not proxied in the Vue instance to prevent conflicts with Vue internalsSee:

**Comment by deatil** [comment]
看下 这个 $data.visible 是哪个文件报错出来的
