### ISSUE TITLE
[Question]: 点击更新权限，报超时错误

### ISSUE THREAD

**Issue by jinxu96** [deatil/larke-admin-frontend#7]
### 疑惑的地方

点击更新权限缓存报
timeout of 5000ms exceeded
![微信截图_20230922143030](https://github.com/deatil/larke-admin-frontend/assets/42291616/0916d459-b9e8-494d-8465-f162aa934f3c)
用户组权限也给了
![微信截图_20230922143043](https://github.com/deatil/larke-admin-frontend/assets/42291616/d08d3fca-8140-4f55-8798-6c2f956946be)
就是那个供应商管理
但是api调用的话报没有访问权限，使用admin账号是可以的，不管我前端有没有增加这个权限

### 期望的结果

给了权限能生效

**Comment by jinxu96** [comment]
![微信截图_20230922143723](https://github.com/deatil/larke-admin-frontend/assets/42291616/9dac35aa-c47d-4e35-8a7f-f4dafd96472d)

**Comment by jinxu96** [comment]
> ### 疑惑的地方
> 点击更新权限缓存报 timeout of 5000ms exceeded ![微信截图_20230922143030](https://user-images.githubusercontent.com/42291616/269850801-0916d459-b9e8-494d-8465-f162aa934f3c.png) 用户组权限也给了 ![微信截图_20230922143043](https://user-images.githubusercontent.com/42291616/269850911-d08d3fca-8140-4f55-8798-6c2f956946be.png) 就是那个供应商管理 但是api调用的话报没有访问权限，使用admin账号是可以的，不管我前端有没有增加这个权限
> 
> ### 期望的结果
> 给了权限能生效

**Comment by deatil** [comment]
超时的话，最好把php的超时时间设置长一些

**Comment by deatil** [comment]
postman提交接口需要加header的token才行

**Comment by jinxu96** [comment]
> postman提交接口需要加header的token才行

我加了的
![微信截图_20230922161914](https://github.com/deatil/larke-admin-frontend/assets/42291616/57dda667-25ee-47b4-b23d-036c28d182d1)

**Comment by deatil** [comment]
需要同步权限成功成功才行。本地测试的话可以把php的超时时间设置长些

**Comment by jinxu96** [comment]
> 需要同步权限成功成功才行。本地测试的话可以把php的超时时间设置长些

php.ini是30s，这个是vue的超时时间吗

**Comment by deatil** [comment]
> > 需要同步权限成功成功才行。本地测试的话可以把php的超时时间设置长些
> 
> php.ini是30s，这个是vue的超时时间吗

vue看起来是50s

**Comment by jinxu96** [comment]
> > > 需要同步权限成功成功才行。本地测试的话可以把php的超时时间设置长些
> > 
> > 
> > php.ini是30s，这个是vue的超时时间吗
> 
> vue看起来是50s

刚看了代码，好像是5000
![微信截图_20230922164313](https://github.com/deatil/larke-admin-frontend/assets/42291616/056eb6a2-5a35-4758-a440-a49c5acb9c65)

**Comment by deatil** [comment]
可以都改一下，5000的话，那就是只有5s

**Comment by jinxu96** [comment]
> > > 需要同步权限成功成功才行。本地测试的话可以把php的超时时间设置长些
> > 
> > 
> > php.ini是30s，这个是vue的超时时间吗
> 
> vue看起来是50s

权限更新成功了
![微信截图_20230922165222](https://github.com/deatil/larke-admin-frontend/assets/42291616/e0f7ee99-581e-4518-b369-00b7b94963b1)
但是还是无法访问，这是为啥

**Comment by deatil** [comment]
账号有授权分组吗

**Comment by jinxu96** [comment]
> 账号有授权分组吗
![微信截图_20230922170927](https://github.com/deatil/larke-admin-frontend/assets/42291616/186fcfb9-2b8b-45ad-b0e8-149c1bc7e0fe)
![微信截图_20230922170940](https://github.com/deatil/larke-admin-frontend/assets/42291616/acf1fcd8-edca-437a-beae-adfce75bee66)
都有

**Comment by deatil** [comment]
那就再同步一次权限，该说是没有问题了的。

**Comment by jinxu96** [comment]
> 那就再同步一次权限，该说是没有问题了的。

![微信截图_20230922171435](https://github.com/deatil/larke-admin-frontend/assets/42291616/70718993-fac1-48f1-8574-e9de5767854d)
![微信截图_20230922171451](https://github.com/deatil/larke-admin-frontend/assets/42291616/44f66023-632f-454b-9206-c2f8b9c88b77)
这配置应该也没啥问题吧

**Comment by deatil** [comment]
> > 那就再同步一次权限，该说是没有问题了的。
> 
> ![微信截图_20230922171435](https://user-images.githubusercontent.com/42291616/269892093-70718993-fac1-48f1-8574-e9de5767854d.png) ![微信截图_20230922171451](https://user-images.githubusercontent.com/42291616/269892110-44f66023-632f-454b-9206-c2f8b9c88b77.png) 这配置应该也没啥问题吧

设置没问题

**Comment by jinxu96** [comment]
![微信截图_20230922172022](https://github.com/deatil/larke-admin-frontend/assets/42291616/e51e9519-e04c-404a-b14d-8a1df7f4fcd8)
![微信截图_20230922172117](https://github.com/deatil/larke-admin-frontend/assets/42291616/5f5e5979-c701-46a0-96a6-3271aaa3c51a)
我添加的规则，为啥在用户组与权限表找不到记录，没添加进去

**Comment by deatil** [comment]
同步权限后可以看 larke_rules 这个表有没有对应数据

**Comment by jinxu96** [comment]
> 同步权限后可以看 larke_rules 这个表有没有对应数据

没有耶

**Comment by jinxu96** [comment]
我找出原因了，傻逼了

**Comment by jinxu96** [comment]
> 同步权限后可以看 larke_rules 这个表有没有对应数据

感谢大佬

**Comment by deatil** [comment]
看你的截图，你把授权授权错了，你有品牌管理和供应商管理。你现在授权的是品牌管理，就品牌管理有效。供应商管理也加上授权就行了

**Comment by jinxu96** [comment]
> 看你的截图，你把授权授权错了，你有品牌管理和供应商管理。你现在授权的是品牌管理，就品牌管理有效。供应商管理也加上授权就行了

是的，还有个问题，为什么，我登录新建的账号，每次登录后会空白页面，然后刷新就会是404面页面，再点击那个404页面的那个按钮就到首页了

**Comment by deatil** [comment]
> > 看你的截图，你把授权授权错了，你有品牌管理和供应商管理。你现在授权的是品牌管理，就品牌管理有效。供应商管理也加上授权就行了
> 
> 是的，还有个问题，为什么，我登录新建的账号，每次登录后会空白页面，然后刷新就会是404面页面，再点击那个404页面的那个按钮就到首页了

开发的时候，加载是需要时间的。有段前置时间加载可能会出现空白，需要加载完后才不会空白。不是新账号有时也会出现段时间空白

**Comment by jinxu96** [comment]
> > > 看你的截图，你把授权授权错了，你有品牌管理和供应商管理。你现在授权的是品牌管理，就品牌管理有效。供应商管理也加上授权就行了
> > 
> > 
> > 是的，还有个问题，为什么，我登录新建的账号，每次登录后会空白页面，然后刷新就会是404面页面，再点击那个404页面的那个按钮就到首页了
> 
> 开发的时候，加载是需要时间的。有段前置时间加载可能会出现空白，需要加载完后才不会空白。不是新账号有时也会出现段时间空白

ok,了解，感谢
